apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-root
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ocppe/gitops-hub.git
    targetRevision: main
    path: argocd-apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
